# config/packages/liip_imagine.yaml
liip_imagine:
    twig:
        mode: lazy
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: 'gd'

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path:
                web_root: '%env(FILES_DIR)%'
                cache_prefix: 'media'

    loaders:
        default:
            filesystem:
                data_root: '%env(FILES_DIR)%'


    # your filter sets are defined here
    # sets the desired resize method: 'outbound' crops the image as required,
    # while 'inset' performs a non-cropping relative resize.
    filter_sets:
        detail:
            filters:
                relative_resize: { heighten: 1080 }
                strip: ~

        square:
            quality: 75
            filters:
                upscale: { min: [770, 770] }
                thumbnail: { size: [120, 120], mode: 'inset' }
                strip: ~
        default_thumbnail:
              quality: 75
              filters:
                upscale: { min: [770, 770] }
                thumbnail: { size: [120, 120], mode: 'inset' }
                strip: ~


        # use the default cache configuration
        cache: ~