# config/preview_export.yaml
preview_export:
    path: /files/tmp/{year}/{month}/{day}/{random}/{subdir}/{file}
    controller: App\Controller\net\exelearning\Controller\Api\OdeExportApiController::previewFile    
    requirements:
        year: \d{4}
        month: \d{2}
        day: \d{2}
        random: .+
        subdir: .+
        file: .+
