monolog:
    handlers:
        main:
            type: stream
            path: php://stdout
            level: debug
            formatter: monolog.formatter.json
            channels: ["!event"]
        error:
            type: stream
            path: php://stderr
            level: error
            formatter: monolog.formatter.json
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deprecation:
            type: stream
            path: php://stderr
            formatter: monolog.formatter.json
            channels: [deprecation]
