# config/routes.yaml

root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/workarea'
        keepQueryParams: false
        permanent: true

healthcheck_redirect:
    path: /healthcheck
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '%base_path%/healthcheck'
        permanent: true        

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
    prefix: '%base_path%'



